name: Unit Tests
on: [push]
jobs:
  sql-diff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Run tests
        working-directory: ./sqldiff
        run: |
          pipenv install --dev
          pipenv run pytest
